# Packages that must never be removed or flagged as junk.

SYSTEM_PACKAGES = [
    "com.android.", "com.android.phone", "com.android.mms",
    "com.android.systemui", "com.google.android.", "com.samsung.", "com.sec.",
    "com.samsung.android.dialer", "com.samsung.android.messaging", "com.miui.",
    "com.xiaomi.", "com.mi.", "com.mipay.", "com.mi.global.", "com.vivo.",
    "com.iqoo.", "com.bbk.", "com.vivo.browser", "com.vivo.assistant",
    "com.realme.", "com.oppo.", "com.coloros.", "com.heytap.", "com.realme.security",
    "com.huawei.", "com.hihonor.", "com.huawei.android.", "com.huawei.hwid",
    "com.huawei.systemmanager", "com.oneplus.", "com.oplus.", "com.oneplus.camera",
    "com.oneplus.security", "com.sony.", "com.sonyericsson.", "com.sonymobile.",
    "com.sony.android.", "com.asus.", "com.zenui.", "com.asus.launcher",
    "com.asus.camera", "com.lenovo.", "com.motorola.", "com.lenovo.launcher",
    "com.motorola.android.", "com.hmdglobal.", "com.nokia.", "com.hmd.",
    "com.lge.", "com.lg.", "com.lge.launcher", "com.lge.systemui",
    "com.gogo.launcher", "com.vsmart.", "com.vinsmart.", "com.tecno.", "com.infinix.",
    "com.transsion.", "com.itel.", "com.hios.",
]

CHAT_WHITELIST = [
    "com.zing.zalo", "com.facebook.katana", "com.facebook.orca",
    "com.tencent.mm", "com.whatsapp", "com.viber.voip",
    "com.telegram.messenger", "jp.naver.line.android",
    "com.ss.android.ugc.trill",
]

POPULAR_APPS_WHITELIST = [
    "com.ss.android.ugc.trill",
    "com.zhiliaoapp.musically",
    "com.instagram.android",
    "com.facebook.katana",
    "com.facebook.orca",
    "com.facebook.lite",
    "com.google.android.youtube",
    "com.google.android.apps.youtube.music",
    "com.ss.android.ugc.aweme",
    "com.viber.voip",
    "com.snapchat.android",
    "com.twitter.android",
    "com.linkedin.android",
    "com.pinterest",
    "com.reddit.frontpage",
    "com.zing.zalo",
    "com.whatsapp",
    "com.tencent.mm",
    "com.telegram.messenger",
    "jp.naver.line.android",
    "com.shopee.vn",
    "com.shopee.id", "com.shopee.th", "com.shopee.ph",
    "vn.lazada",
    "com.tiki.vn",
    "com.sendo.vn",
    "com.bestprice.vn",
    "com.netflix.mediaclient",
    "com.spotify.music",
    "com.spotify.lite",
    "com.spotify.tv.android",
    "com.mxtech.videoplayer.ad",
    "com.videomedia.video",
    "com.vng.vngmedia",
    "com.fpt.vnplay",
    "com.google.android.gm",
    "com.microsoft.office.outlook",
    "com.google.android.apps.maps",
    "com.ubercab", "com.ubercab.eats",
    "com.grab.passenger", "com.grab.passenger.vn",
    "com.beetech.beetech_go",
    "com.garena.game.freefire",
    "com.supercell.clashofclans",
    "com.mobile.legends",
    "com.openai.chatgpt",
    "com.openai.chat",
    "com.openai.chatgpt.android",
    "ai.x.grok",
    "com.xai.grok",
    "com.google.android.apps.bard",
    "com.google.android.apps.genai",
    "com.anthropic.claude",
    "com.deepseek.chat",
    "com.microsoft.copilot",
    "com.tiktok.android",
    "com.zhiliaoapp.musically.go",
]

POPULAR_APP_PREFIXES = (
    "com.ss.android.",
    "com.zhiliaoapp.",
    "com.instagram.",
    "com.facebook.",
    "com.google.android.apps.youtube",
    "com.shopee.",
    "vn.lazada",
    "com.tiki.",
)

BANK_APPS_WHITELIST = [
    "com.vietinbank.ipay",
    "com.vietcombank.mobilebanking",
    "vn.com.techcombank.bb.app",
    "com.tpb.mb.gprsandroid",
    "com.mbbank",
    "vn.vnpay.wallet",
    "com.sacombank.mobilebanking",
    "com.vpbank.mobile",
    "com.shb.mobile",
    "com.bidv.mobilebanking",
    "vn.abcbank.mobilebanking",
    "com.ocb.ewallet",
    "com.seabank.mb",
    "com.hdbank.mobilebanking",
    "com.eximbank.ebanking",
    "com.vietabank.mobilebanking",
    "com.baca.bank",
    "com.pgbank.mobilebanking",
    "com.lienvietpostbank.mbank",
    "com.namabank.mobilebanking",
    "com.saigonbank.mobilebanking",
    "com.bvb.mobilebanking",
    "com.ncb.ebanking",
    "com.vietbank.mobilebanking",
    "com.kienlongbank.mobilebanking",
    "com.msbbank.mobilebanking",
    "com.oceanbank.mobilebanking",
    "com.gpbank.mobilebanking",
    "com.scb.ebanking",
    "com.dongabank.mobilebanking",
    "com.vietcapitalbank.mobilebanking",
    "com.publicbank.mobilebanking",
    "com.cbbank.mobilebanking",
    "com.indovinabank.mobilebanking",
    "com.shinhanbank.vn",
    "com.hanabank.mobilebanking",
    "com.citibank.vn",
    "com.hsbc.vn",
    "com.standardchartered.vn",
    "com.uob.mobilebanking",
    "com.viettelpay",
    "com.zalopay",
    "com.moca",
    "com.airpay",
]

TRUSTED_ANALYSIS_PACKAGES = frozenset(
    set(POPULAR_APPS_WHITELIST) | set(CHAT_WHITELIST) | set(BANK_APPS_WHITELIST)
)
